version: "3.9"

services:
  web:
    build: .
    container_name: stock_web
    ports:
      - "6767:80"   # Akses di localhost:6767
    networks:
      - databases2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stock_phpmyadmin
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
    ports:
      - "6565:80"
    networks:
      - databases2

networks:
  databases2:
    external: true
